apiVersion: v1
appVersion: v1.2.7
description: Prometheus metrics exporter for Kafka
home: https://gkarthiks.github.io/helm-charts/charts/prometheus-kafka-exporter
keywords:
- prometheus
- kafka
maintainers:
- email: github.gkarthiks@gmail.com
  name: gkarthiks
- email: devops@yalo.com
  name: yalochat
name: prometheus-kafka-exporter
sources:
- https://github.com/danielqsj/kafka_exporter
- https://github.com/yalochat/kafka-prometheus-exporterter
version: 0.2.0
