apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prometheus-kafka-exporter
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        key: prometheus-kafka-exporter-secret
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: common-sec-ops-cluster-secret-store
  target:
    creationPolicy: Owner
